# Generated by Django 4.0.2 on 2022-02-16 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_inventory_quantitiy_product_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(default='N/A', max_length=999),
            preserve_default=False,
        ),
    ]
